//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<System.DateTime> IncomeMonth { get; set; }
        public int ClientIncomes { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
