//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public int Id { get; set; }
        public Nullable<decimal> Cleaning_Tools { get; set; }
        public Nullable<decimal> Worker_salary { get; set; }
        public Nullable<System.DateTime> OutcomeMonth { get; set; }
    }
}
